In [34]:
import os
import csv
import random
import numpy as np

In [27]:
data_dir = "/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/trecvid_2019/"
results_npy = os.path.join(data_dir, "results.npy")
results = np.load(results_npy)

In [28]:
results[:, 0]

array([ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  4,
        5,  6,  7,  4,  5,  6,  7,  8,  9, 10, 11, 12,  8,  9, 10, 11, 12,
        8,  9, 10, 11, 12, 16, 17, 18, 19, 20, 21, 18, 19, 20, 21, 22, 22,
       23, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [56]:
with open(os.path.join(data_dir, "query/features.csv"), "r") as f:
    reader = csv.reader(f, delimiter=" ")
    query_dict = {int(r[3]): [r[5], int(r[6])] for r in reader}

In [57]:
with open(os.path.join(data_dir, "gallery/features.csv"), "r") as f:
    reader = csv.reader(f, delimiter=" ")
    gallery_dict = {int(r[3]): [r[5], int(r[6]), int(r[7])] for r in reader}

In [59]:
# idx = random.randint(0, 60)
idx = 0
print("query idx :", idx)
print("query :", query_dict[results[idx, 0]])

for r in results[idx][1:]:
    print(gallery_dict[r])

query idx : 0
query : ['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/trecvid_2019/detected_query_videos/clip1_011_id_8.mp4', 1]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot164_1222_id_1755370.mp4', 99, 6]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot95_79_id_1043179.mp4', 99, 8]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot126_1918_id_1351271.mp4', 99, 13]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot155_838_id_1656133.mp4', 99, 8]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot155_736_id_1655700.mp4', 99, 8]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot25_279_id_265410.mp4', 99, 5]
['/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot187_432_id_1981278.mp4', 99, 13]
['/net/per610a/export/das18a/satoh-lab/sha

In [15]:
with open(os.path.join(data_dir, "gallery/features.csv"), "r") as f:
    reader = csv.reader(f, delimiter=" ")
    for r in reader:
        if int(r[3]) == 84497:
            print(r)

['7877', '376626', '223480', '84497', '7876', '/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot195_124_id_2054603.mp4', '99', '5']
['32660', '376626', '223480', '84497', '32659', '/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot195_124_id_2054603.mp4', '99', '5']
['58278', '376626', '223480', '84497', '58277', '/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot195_124_id_2054603.mp4', '99', '5']
['76996', '376626', '223480', '84497', '76995', '/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot195_124_id_2054603.mp4', '99', '5']
['127610', '376626', '223480', '84497', '127609', '/net/per610a/export/das18a/satoh-lab/share/datasets/eastenders/video_detected/shot195_124_id_2054603.mp4', '99', '6']


In [26]:
r = results[0].tolist()
np.array(sorted(set(r), key=r.index))

array([     0, 213535,  31350, 165993, 234557,  80850,  24343,  61872,
       226869, 139260, 227084,  98547, 149424, 229904, 148135,  84114,
       217070, 245618, 190964,  80611,  61568, 136030,  29021,  91481,
       239799, 145621, 189399, 248498,  24558,  58876, 171950, 258350,
         3355, 248099,  36998,  90474,  19727,  45532, 190951, 106902,
       166796, 104784, 226389, 152446, 125811, 194069, 249346, 213769,
       135563,  54392,  25868, 192176,  94238, 185714, 235987, 199698,
       236809, 101374, 116408,  19070, 195369, 115950, 176636,  25637,
       201313, 209362, 182304, 154530, 197737, 149707, 178713, 200577,
        35533, 242595, 152856, 178620, 221058, 166902, 108866])

In [23]:
_, idx = np.unique(results[0], return_index=True)
results[0][np.sort(idx)]

array([     0, 213535,  31350, 165993, 234557,  80850,  24343,  61872,
       226869, 139260, 227084,  98547, 149424, 229904, 148135,  84114,
       217070, 245618, 190964,  80611,  61568, 136030,  29021,  91481,
       239799, 145621, 189399, 248498,  24558,  58876, 171950, 258350,
         3355, 248099,  36998,  90474,  19727,  45532, 190951, 106902,
       166796, 104784, 226389, 152446, 125811, 194069, 249346, 213769,
       135563,  54392,  25868, 192176,  94238, 185714, 235987, 199698,
       236809, 101374, 116408,  19070, 195369, 115950, 176636,  25637,
       201313, 209362, 182304, 154530, 197737, 149707, 178713, 200577,
        35533, 242595, 152856, 178620, 221058, 166902, 108866])

In [ ]:
[213535  31350 165993 234557  80850  24343  61872 226869 139260 227084
  98547 149424 229904 148135  84114 217070 245618 190964  80611  61568
 136030  29021  91481 239799 145621 189399 248498  24558  58876 171950
 258350   3355 248099  36998  90474  19727  45532 190951 106902 166796
 104784 226389 152446 125811 194069 249346 213769 135563  54392  25868
 192176  94238 185714 235987 199698 236809 101374 116408  19070 195369
 115950 176636  25637 201313 209362 182304 154530 197737 149707 178713
 200577  35533 242595 152856 178620 221058 166902 108866 129218 193789
  14507  37673 209931 171591  38409  61810 203757 204261 237251 258403
 135047 242235 168746  15122  71014 124041 246736 160347  90295 100364]