In [2]:
import numpy as np

features = np.load("../data/features/kinetics_100.npy")
labels = np.load("../data/features/kinetics_100_labels.npy")

In [4]:
features.shape

(48, 2304)

In [6]:
labels

array([[44,  3],
       [19,  1],
       [22,  1],
       [41,  3],
       [29,  2],
       [25,  2],
       [18,  1],
       [39,  3],
       [23,  1],
       [ 4,  0],
       [20,  1],
       [ 2,  0],
       [36,  3],
       [15,  1],
       [32,  2],
       [33,  2],
       [ 1,  0],
       [26,  2],
       [13,  1],
       [ 3,  0],
       [40,  3],
       [31,  2],
       [10,  0],
       [27,  2],
       [21,  1],
       [14,  1],
       [30,  2],
       [12,  1],
       [35,  2],
       [ 5,  0],
       [ 0,  0],
       [ 6,  0],
       [37,  3],
       [28,  2],
       [38,  3],
       [43,  3],
       [46,  3],
       [11,  0],
       [45,  3],
       [47,  3],
       [ 9,  0],
       [24,  2],
       [ 8,  0],
       [17,  1],
       [42,  3],
       [34,  2],
       [ 7,  0],
       [16,  1]])

In [8]:
features[30]

array([0.00815229, 0.00084763, 0.0009454 , ..., 0.15005532, 0.05517099,
       0.        ], dtype=float32)

In [10]:
features[27] == features[30]

array([ True,  True,  True, ...,  True,  True,  True])

In [11]:
labels[:, 1]

array([3, 1, 1, 3, 2, 2, 1, 3, 1, 0, 1, 0, 3, 1, 2, 2, 0, 2, 1, 0, 3, 2,
       0, 2, 1, 1, 2, 1, 2, 0, 0, 0, 3, 2, 3, 3, 3, 0, 3, 3, 0, 2, 0, 1,
       3, 2, 0, 1])

In [20]:
np.mean(features[np.where(labels[:, 1] == 3)], axis=0).shape

(2304,)

In [23]:
fvs = np.array([np.mean(features[np.where(labels[:, 1] == idx)], axis=0) for idx in range(int(len(features) / 12))])

In [29]:
for i in range(len(fvs)):
    for j in range(i+1, len(fvs)):
        print(i, j, fvs[i] == fvs[j])

0 1 [ True False False ...  True False  True]
0 2 [False  True False ...  True False  True]
0 3 [ True  True  True ... False  True  True]
1 2 [False False  True ...  True  True  True]
1 3 [ True False False ... False False  True]
2 3 [False  True False ... False False  True]


In [30]:
fvs

array([[0.04242902, 0.00945257, 0.02600949, ..., 0.19738941, 0.02332885,
        0.00022898],
       [0.04242902, 0.00945256, 0.02600948, ..., 0.19738941, 0.02332884,
        0.00022898],
       [0.04242901, 0.00945257, 0.02600948, ..., 0.19738941, 0.02332884,
        0.00022898],
       [0.04242902, 0.00945257, 0.02600949, ..., 0.19738942, 0.02332885,
        0.00022898]], dtype=float32)

In [32]:
a = np.load("../data/eastenders/feature_label_32/feature_0.npy")

In [33]:
len(a)

278968